### ISSUE TITLE
Website should be accessible via https://psconf.eu

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#47]
I think it would be a good idea to enable https for the website

**Comment by TobiasPSP** [comment]
The registration form used for delegate registration will be a https connection so we are safe here. I agree it would be even better to have the entire site use http!

**Comment by gravejester** [comment]
https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by kilasuit** [comment]
@SQLDBAWithABeard - Unfortunately with it being a github pages site we cannot make the site https whilst using a custom domain - however we could host elsewhere but we would need to decide how much of a priority that would be as there would be a level of effort to enable rehosting the site elsewhere due to reliance on the Jekyll engine in the back end.

**Comment by SQLDBAWithABeard** [comment]
We don't want interruption now that marketing is in full flow and we have attendees, sponsors and speakers making use of the site. Probably best to close this and revisit for next year

**Comment by kilasuit** [comment]
@gravejester since this issue was raised GH have enabled Custom domains to be able to force the use https via a checkbox in the repository settings.

could this be flicked on now?

**Comment by stuartpreston** [comment]
Closing this as the site is now available over TLS at https://psconf.eu
